# fichier de configuration de CoNext-bot

# Parametrage de la source permettant le téléchargement/mise à jour du script
downloadsource="https://raw.githubusercontent.com/BANQUE-DU-NUMERIQUE/ABN-Bot/main/"

# Adresse de téléchargement de GLPI Agent (avec snap)
glpiagentinstallurl="https://github.com/glpi-project/glpi-agent/releases/download/1.15/glpi-agent-1.15-linux-installer.pl"

# Nom et emplacement du répertoire contenant les fichiers logs
logpath="log"

# Adresse du serveur GLPI
glpiserver="https://adeladn.fr35.glpi-network.cloud"

glpi_user_token="qEG4CiozYfTse1VZCNEIe9kEZEvNzmS3GdgnNSKb"
glpi_app_token="WfXeIR5jqOtUsI1orCWuqXnANPsm3WiKpfo7v9cc"
glpi_doc_category_id=1 

# Adresse et chemin du dossier NFS devant recevoir les fichiers logs
nfspath="127.0.0.1:/mnt/Path/To/Logs"

# Configuration des paramètres FTP du serveur devant recevoir les fichiers logs
ftphost=''
ftpuser=''
ftppassword=''
ftpdirectory='/'

# Méthode d'effacement pour Nwipe (https://github.com/martijnvanbrummelen/nwipe/blob/master/man/nwipe.1)
nwipemethod="quick"
